#default configuration, this can be edited, and should be copied to a new file in case of upgrade
grokDirectory: ./grok
jobDirectory: ./jobs

#we will create the job files here: {analyticsDirectory}/conf/job
#this is optional, we will try and determine this automatically
#analyticsDirectory: ../analytics-agent

#operating system specific commands
psCommand: "/bin/ps -ef"
lsofCommand: "/usr/sbin/lsof -p %d"

#windows would have these:
#psCommand: pslist.exe
#lsofCommand: "handle.exe -p %d"
#to download pslist, https://download.sysinternals.com/files/PSTools.zip
#to download handle.exe, https://download.sysinternals.com/files/Handle.zip


process:
  - java
  - -Dappdynamics.com

logs:
  - /var/log/*.log

#optionally, you can exclude log files where the absolutely path matches a given regex pattern:
#excludeLogs:
#  - .*appdynamics.*